import configparser
import os.path
from pathlib import Path

DEFAULT_HAMILTONIAN_PROBABILITY = 0.8

RESULTS_SIZE_GENERALIZATION_PLOT_DATASET_SIZES = [25, 50, 100, 150, 200]
RESULTS_P_PARAM_GENERALIZATION_PLOT_HAM_PROBABILITY = [
    max(DEFAULT_HAMILTONIAN_PROBABILITY - 0.1, DEFAULT_HAMILTONIAN_PROBABILITY / 2),
    DEFAULT_HAMILTONIAN_PROBABILITY,
    min(DEFAULT_HAMILTONIAN_PROBABILITY + 0.1, DEFAULT_HAMILTONIAN_PROBABILITY / 2 + 0.5)]
RESULTS_SUPERCRITICAL_REGIME_ER_P_PARAM = 0.25
DATASET_SIZE_ACCURACY_VARIANCE_002_95PERC_CONF = 5000

CONFIG_FILE_PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "config.cfg"))
config = configparser.ConfigParser()
config.read(CONFIG_FILE_PATH)
MODEL_WEIGHTS_FOLDER = config["MODELS"]["MODEL_WEIGHTS_FOLDER"]
CONCORDE_SCRIPT_PATH = config["CONCORDE"]["CONCORDE_SCRIPT_PATH"]
CONCORDE_WORK_DIR = config["CONCORDE"]["CONCORDE_WORK_DIR"]
CONCORDE_INPUT_FILE = config["CONCORDE"]["CONCORDE_INPUT_FILE"]
WEIGHTS_BACKUP_PATH = config["DATABASE"]["WEIGHTS_BACKUP_PATH"]
EVALUATION_DATABASE_LOCK_PATH = config["DATABASE"]["EVALUATION_DATABASE_LOCK_PATH"]
WEIGHTS_AND_BIASES_PROJECT = config["LOGGING"]["WEIGHTS_AND_BIASES_PROJECT"]

MAX_NR_BATCHES_TO_USE_FOR_EVALUATION = 10
ROOT_DATA_DIR = Path(config["DATABASE"]["ROOT_DATA_DIR"])
GRAPH_DATA_DIRECTORY_QUICK_EVALUATION = ROOT_DATA_DIR / "VAL_DATA"
GRAPH_DATA_DIRECTORY_SIZE_GENERALISATION = ROOT_DATA_DIR / "SIZE_GENERALISATION_DATA"
GRAPH_DATA_DIRECTORY_HAM_PROB_GENERALISATION = ROOT_DATA_DIR / "HAM_PROB_PARAM_GENERALISATION_DATA"
GRAPH_DATA_DIRECTORY_SUPERCRITICAL_CASE = ROOT_DATA_DIR / "SUPERCRITICAL_DATA"
FHCP_BENCHMARK_DIR = config["DATABASE"]["FHCP_BENCHMARK_DIR"]
EVALUATION_MINIMAL_TEST_DATA_FOLDERS = ["DATA/Erdos_Renyi(25,02453).pt"]

MODEL_CHECKPOINT_SAVING_DIRECTORY = config["LOGGING"]["CHECKPOINT_STORAGE_DIRECTORY"]
WANDB_DIRECTORY = config["LOGGING"]["WANDB_DIRECTORY"]

DEFAULT_FINAL_TEST_TAG = "test/ER_80"

FHCP_HOMEPAGE = "https://sites.flinders.edu.au/flinders-hamiltonian-cycle-project/fhcp-challenge-set/"
FHCP_GRAPHS_URL = "http://sites.flinders.edu.au/flinders-hamiltonian-cycle-project/wp-content/uploads/sites/18/2020/01/FHCPCS.7z"
FHCP_SOLUTIONS_URL = "http://sites.flinders.edu.au/flinders-hamiltonian-cycle-project/wp-content/uploads/sites/18/2020/01/FHCPCS_sols.7z"
